-- 코드를 입력하세요
SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE * SALES) AS TOTAL_SALES
FROM AUTHOR A 
JOIN BOOK B ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE SALES_DATE LIKE '%2022-01%'
GROUP BY A.AUTHOR_ID, CATEGORY, AUTHOR_NAME
ORDER BY A.AUTHOR_ID, CATEGORY DESC