SELECT 
    car_id,
    ROUND(AVG(DATEDIFF(END_DATE, START_DATE) + 1), 1) AS AVERAGE_DURATION
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY 
    car_id
HAVING 
    AVG(DATEDIFF(END_DATE, START_DATE) + 1) >= 7
ORDER BY
    AVERAGE_DURATION desc,
    car_id desc
