-- 코드를 입력하세요
SELECT A.APNT_NO, PT_NAME, A.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM DOCTOR D
JOIN APPOINTMENT A ON D.DR_ID = A.MDDR_ID
JOIN PATIENT P ON A.PT_NO = P.PT_NO
WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS'
ORDER BY APNT_YMD